### ISSUE TITLE
A possible bug in alpha_mtgp.m

### ISSUE THREAD

**Issue by hao-peng** [ebonilla/mtgp#1]
In alpha_mtgp.m
On line 45:  `n = length(nx);` 

nx is always a scalar.

It should be changed to:
`n = length(y);`

However, it does affect the result, if MIN_NOISE = 0.

**Comment by ebonilla** [comment]
I hope you managed to solve this issue. nx  is the actual number of times each element of y has been observed, so it is a vector (which in the most common case has all entries 1).

**Comment by hao-peng** [comment]
I found I was wrong about nx, so I closed this issue. I am sorry about my wrong report. Thanks for your reply!
